# Generated by Django 2.1 on 2018-08-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
