# Generated by Django 2.1 on 2018-08-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20180823_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, default='B64encoded', max_length=100),
        ),
    ]
