# Generated by Django 2.1 on 2018-08-26 02:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_auto_20180824_0153'),
        ('bookrequest', '0002_auto_20180826_0246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrequest',
            unique_together={('user', 'book')},
        ),
    ]
