# Generated by Django 2.1 on 2018-08-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0005_bookrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='state',
            field=models.IntegerField(choices=[(0, 'Enviada'), (1, 'Aceptada'), (2, 'Entregado'), (3, 'Devuelto/Finalizada'), (4, 'Rechazada/Finalizada')], default=0),
        ),
    ]
