# Generated by Django 2.1 on 2018-11-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
