# Generated by Django 2.1 on 2018-11-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181113_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
