# Generated by Django 2.1 on 2018-08-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrequest',
            unique_together=set(),
        ),
    ]
