# Generated by Django 2.1 on 2018-08-26 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0003_auto_20180826_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
