# Generated by Django 2.1 on 2018-11-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0006_auto_20180828_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='state',
            field=models.IntegerField(choices=[(0, 'Enviada'), (1, 'Aceptada'), (2, 'Entregado-SinConfirmacion'), (3, 'Entregado-Confirmado'), (4, 'Devuelto-SinConfirmacion'), (5, 'Devuelto-Confirmado'), (6, 'Rechazada/Finalizada')], default=0),
        ),
    ]
