# Generated by Django 2.1 on 2018-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0007_auto_20181112_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='calif_owner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='calif_reader',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='state',
            field=models.IntegerField(choices=[(0, 'Enviada'), (1, 'Aceptada'), (2, 'Entregado-SinConfirmacion'), (3, 'Entregado-Confirmado'), (4, 'Devuelto-SinConfirmacion'), (5, 'Devuelto-Confirmado-Sin-Calificar'), (6, 'Rechazada/Finalizada'), (7, 'Devuelto-Calificado-Owner'), (8, 'Devuelto-Calificado-Reader'), (9, 'Devuelto')], default=0),
        ),
    ]
